// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authenticator.proto

package dbauth_authenticator_protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DBUserRequest struct {
	IamRoleArn              string   `protobuf:"bytes,1,opt,name=iam_role_arn,json=iamRoleArn,proto3" json:"iam_role_arn,omitempty"`
	SignedGetCallerIdentity string   `protobuf:"bytes,2,opt,name=signed_get_caller_identity,json=signedGetCallerIdentity,proto3" json:"signed_get_caller_identity,omitempty"`
	Dbname                  string   `protobuf:"bytes,3,opt,name=dbname,proto3" json:"dbname,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DBUserRequest) Reset()         { *m = DBUserRequest{} }
func (m *DBUserRequest) String() string { return proto.CompactTextString(m) }
func (*DBUserRequest) ProtoMessage()    {}
func (*DBUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{0}
}

func (m *DBUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUserRequest.Unmarshal(m, b)
}
func (m *DBUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUserRequest.Marshal(b, m, deterministic)
}
func (m *DBUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUserRequest.Merge(m, src)
}
func (m *DBUserRequest) XXX_Size() int {
	return xxx_messageInfo_DBUserRequest.Size(m)
}
func (m *DBUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DBUserRequest proto.InternalMessageInfo

func (m *DBUserRequest) GetIamRoleArn() string {
	if m != nil {
		return m.IamRoleArn
	}
	return ""
}

func (m *DBUserRequest) GetSignedGetCallerIdentity() string {
	if m != nil {
		return m.SignedGetCallerIdentity
	}
	return ""
}

func (m *DBUserRequest) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

type DBHashRequest struct {
	IamRoleArn              string   `protobuf:"bytes,1,opt,name=iam_role_arn,json=iamRoleArn,proto3" json:"iam_role_arn,omitempty"`
	SignedGetCallerIdentity string   `protobuf:"bytes,2,opt,name=signed_get_caller_identity,json=signedGetCallerIdentity,proto3" json:"signed_get_caller_identity,omitempty"`
	Dbname                  string   `protobuf:"bytes,3,opt,name=dbname,proto3" json:"dbname,omitempty"`
	Salt                    []byte   `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DBHashRequest) Reset()         { *m = DBHashRequest{} }
func (m *DBHashRequest) String() string { return proto.CompactTextString(m) }
func (*DBHashRequest) ProtoMessage()    {}
func (*DBHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{1}
}

func (m *DBHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBHashRequest.Unmarshal(m, b)
}
func (m *DBHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBHashRequest.Marshal(b, m, deterministic)
}
func (m *DBHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBHashRequest.Merge(m, src)
}
func (m *DBHashRequest) XXX_Size() int {
	return xxx_messageInfo_DBHashRequest.Size(m)
}
func (m *DBHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DBHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DBHashRequest proto.InternalMessageInfo

func (m *DBHashRequest) GetIamRoleArn() string {
	if m != nil {
		return m.IamRoleArn
	}
	return ""
}

func (m *DBHashRequest) GetSignedGetCallerIdentity() string {
	if m != nil {
		return m.SignedGetCallerIdentity
	}
	return ""
}

func (m *DBHashRequest) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

func (m *DBHashRequest) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type DBUserResponse struct {
	Dbuser               string   `protobuf:"bytes,1,opt,name=dbuser,proto3" json:"dbuser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUserResponse) Reset()         { *m = DBUserResponse{} }
func (m *DBUserResponse) String() string { return proto.CompactTextString(m) }
func (*DBUserResponse) ProtoMessage()    {}
func (*DBUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{2}
}

func (m *DBUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUserResponse.Unmarshal(m, b)
}
func (m *DBUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUserResponse.Marshal(b, m, deterministic)
}
func (m *DBUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUserResponse.Merge(m, src)
}
func (m *DBUserResponse) XXX_Size() int {
	return xxx_messageInfo_DBUserResponse.Size(m)
}
func (m *DBUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DBUserResponse proto.InternalMessageInfo

func (m *DBUserResponse) GetDbuser() string {
	if m != nil {
		return m.Dbuser
	}
	return ""
}

type DBHashResponse struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBHashResponse) Reset()         { *m = DBHashResponse{} }
func (m *DBHashResponse) String() string { return proto.CompactTextString(m) }
func (*DBHashResponse) ProtoMessage()    {}
func (*DBHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{3}
}

func (m *DBHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBHashResponse.Unmarshal(m, b)
}
func (m *DBHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBHashResponse.Marshal(b, m, deterministic)
}
func (m *DBHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBHashResponse.Merge(m, src)
}
func (m *DBHashResponse) XXX_Size() int {
	return xxx_messageInfo_DBHashResponse.Size(m)
}
func (m *DBHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DBHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DBHashResponse proto.InternalMessageInfo

func (m *DBHashResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*DBUserRequest)(nil), "dbauth.authenticator.protos.DBUserRequest")
	proto.RegisterType((*DBHashRequest)(nil), "dbauth.authenticator.protos.DBHashRequest")
	proto.RegisterType((*DBUserResponse)(nil), "dbauth.authenticator.protos.DBUserResponse")
	proto.RegisterType((*DBHashResponse)(nil), "dbauth.authenticator.protos.DBHashResponse")
}

func init() { proto.RegisterFile("authenticator.proto", fileDescriptor_e86ec39f7c35dea3) }

var fileDescriptor_e86ec39f7c35dea3 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x91, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0x9b, 0xff, 0x3f, 0x14, 0x3a, 0xb4, 0x1e, 0x56, 0xd0, 0x50, 0x2f, 0x61, 0xf1, 0x10,
	0x14, 0x72, 0xd0, 0xa3, 0xa7, 0xaa, 0x50, 0xbd, 0x06, 0x3c, 0x87, 0x4d, 0x33, 0x36, 0x81, 0x64,
	0xb7, 0xee, 0x4c, 0x0e, 0xbe, 0x80, 0x0f, 0xe1, 0xcb, 0xf9, 0x2a, 0x92, 0xcd, 0x2a, 0x11, 0xc4,
	0x7a, 0xf3, 0x36, 0x93, 0xef, 0x97, 0x7c, 0xdf, 0xe4, 0x83, 0x43, 0xd5, 0x71, 0x85, 0x9a, 0xeb,
	0x8d, 0x62, 0x63, 0xd3, 0x9d, 0x35, 0x6c, 0xc4, 0x49, 0x59, 0xf4, 0x8f, 0xd3, 0x6f, 0x34, 0x92,
	0x2f, 0x01, 0x2c, 0x6e, 0xaf, 0x1f, 0x08, 0x6d, 0x86, 0x4f, 0x1d, 0x12, 0x8b, 0x18, 0xe6, 0xb5,
	0x6a, 0x73, 0x6b, 0x1a, 0xcc, 0x95, 0xd5, 0x51, 0x10, 0x07, 0xc9, 0x2c, 0x83, 0x5a, 0xb5, 0x99,
	0x69, 0x70, 0x65, 0xb5, 0xb8, 0x82, 0x25, 0xd5, 0x5b, 0x8d, 0x65, 0xbe, 0x45, 0xce, 0x37, 0xaa,
	0x69, 0xd0, 0xe6, 0x75, 0xd9, 0x7f, 0x9b, 0x9f, 0xa3, 0x7f, 0x8e, 0x3f, 0x1e, 0x88, 0x35, 0xf2,
	0x8d, 0xd3, 0xef, 0xbd, 0x2c, 0x8e, 0x60, 0x5a, 0x16, 0x5a, 0xb5, 0x18, 0xfd, 0x77, 0xa0, 0xdf,
	0xe4, 0xab, 0x0b, 0x72, 0xa7, 0xa8, 0xfa, 0xdb, 0x20, 0x42, 0x40, 0x48, 0xaa, 0xe1, 0x28, 0x8c,
	0x83, 0x64, 0x9e, 0xb9, 0x59, 0x26, 0x70, 0xf0, 0xf1, 0x93, 0x68, 0x67, 0x34, 0xe1, 0xf0, 0x76,
	0x47, 0x68, 0x7d, 0x2c, 0xbf, 0xc9, 0xd3, 0x9e, 0x1c, 0xae, 0xf0, 0xa4, 0x80, 0xb0, 0x52, 0x54,
	0x79, 0xce, 0xcd, 0x17, 0x6f, 0x01, 0x2c, 0x56, 0xe3, 0x3a, 0xc4, 0x23, 0xcc, 0xd6, 0xc8, 0x83,
	0x89, 0x38, 0x4b, 0x7f, 0xa8, 0x2c, 0xfd, 0x52, 0xd7, 0xf2, 0xfc, 0x57, 0xec, 0x90, 0x45, 0x4e,
	0x3e, 0x7d, 0xfa, 0x88, 0x7b, 0x7d, 0x46, 0x6d, 0xec, 0xf5, 0x19, 0xdf, 0x2c, 0x27, 0xc5, 0xd4,
	0x09, 0x97, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0x44, 0xca, 0xdc, 0x92, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthenticatorClient is the client API for Authenticator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticatorClient interface {
	GetDBUser(ctx context.Context, in *DBUserRequest, opts ...grpc.CallOption) (*DBUserResponse, error)
	GetDBHash(ctx context.Context, in *DBHashRequest, opts ...grpc.CallOption) (*DBHashResponse, error)
}

type authenticatorClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticatorClient(cc *grpc.ClientConn) AuthenticatorClient {
	return &authenticatorClient{cc}
}

func (c *authenticatorClient) GetDBUser(ctx context.Context, in *DBUserRequest, opts ...grpc.CallOption) (*DBUserResponse, error) {
	out := new(DBUserResponse)
	err := c.cc.Invoke(ctx, "/dbauth.authenticator.protos.Authenticator/GetDBUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticatorClient) GetDBHash(ctx context.Context, in *DBHashRequest, opts ...grpc.CallOption) (*DBHashResponse, error) {
	out := new(DBHashResponse)
	err := c.cc.Invoke(ctx, "/dbauth.authenticator.protos.Authenticator/GetDBHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticatorServer is the server API for Authenticator service.
type AuthenticatorServer interface {
	GetDBUser(context.Context, *DBUserRequest) (*DBUserResponse, error)
	GetDBHash(context.Context, *DBHashRequest) (*DBHashResponse, error)
}

// UnimplementedAuthenticatorServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticatorServer struct {
}

func (*UnimplementedAuthenticatorServer) GetDBUser(ctx context.Context, req *DBUserRequest) (*DBUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDBUser not implemented")
}
func (*UnimplementedAuthenticatorServer) GetDBHash(ctx context.Context, req *DBHashRequest) (*DBHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDBHash not implemented")
}

func RegisterAuthenticatorServer(s *grpc.Server, srv AuthenticatorServer) {
	s.RegisterService(&_Authenticator_serviceDesc, srv)
}

func _Authenticator_GetDBUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).GetDBUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbauth.authenticator.protos.Authenticator/GetDBUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).GetDBUser(ctx, req.(*DBUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticator_GetDBHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).GetDBHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbauth.authenticator.protos.Authenticator/GetDBHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).GetDBHash(ctx, req.(*DBHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authenticator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbauth.authenticator.protos.Authenticator",
	HandlerType: (*AuthenticatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDBUser",
			Handler:    _Authenticator_GetDBUser_Handler,
		},
		{
			MethodName: "GetDBHash",
			Handler:    _Authenticator_GetDBHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authenticator.proto",
}
