// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authenticator.proto

package dbauth_authenticator_protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PGMD5HashRequest struct {
	SignedGetCallerIdentity string   `protobuf:"bytes,1,opt,name=signed_get_caller_identity,json=signedGetCallerIdentity,proto3" json:"signed_get_caller_identity,omitempty"`
	ClaimedIamArn           string   `protobuf:"bytes,2,opt,name=claimed_iam_arn,json=claimedIamArn,proto3" json:"claimed_iam_arn,omitempty"`
	Dbhost                  string   `protobuf:"bytes,3,opt,name=dbhost,proto3" json:"dbhost,omitempty"`
	Dbuser                  string   `protobuf:"bytes,4,opt,name=dbuser,proto3" json:"dbuser,omitempty"`
	Salt                    []byte   `protobuf:"bytes,5,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *PGMD5HashRequest) Reset()         { *m = PGMD5HashRequest{} }
func (m *PGMD5HashRequest) String() string { return proto.CompactTextString(m) }
func (*PGMD5HashRequest) ProtoMessage()    {}
func (*PGMD5HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{0}
}

func (m *PGMD5HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGMD5HashRequest.Unmarshal(m, b)
}
func (m *PGMD5HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGMD5HashRequest.Marshal(b, m, deterministic)
}
func (m *PGMD5HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGMD5HashRequest.Merge(m, src)
}
func (m *PGMD5HashRequest) XXX_Size() int {
	return xxx_messageInfo_PGMD5HashRequest.Size(m)
}
func (m *PGMD5HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PGMD5HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PGMD5HashRequest proto.InternalMessageInfo

func (m *PGMD5HashRequest) GetSignedGetCallerIdentity() string {
	if m != nil {
		return m.SignedGetCallerIdentity
	}
	return ""
}

func (m *PGMD5HashRequest) GetClaimedIamArn() string {
	if m != nil {
		return m.ClaimedIamArn
	}
	return ""
}

func (m *PGMD5HashRequest) GetDbhost() string {
	if m != nil {
		return m.Dbhost
	}
	return ""
}

func (m *PGMD5HashRequest) GetDbuser() string {
	if m != nil {
		return m.Dbuser
	}
	return ""
}

func (m *PGMD5HashRequest) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type PGMD5HashResponse struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PGMD5HashResponse) Reset()         { *m = PGMD5HashResponse{} }
func (m *PGMD5HashResponse) String() string { return proto.CompactTextString(m) }
func (*PGMD5HashResponse) ProtoMessage()    {}
func (*PGMD5HashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{1}
}

func (m *PGMD5HashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGMD5HashResponse.Unmarshal(m, b)
}
func (m *PGMD5HashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGMD5HashResponse.Marshal(b, m, deterministic)
}
func (m *PGMD5HashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGMD5HashResponse.Merge(m, src)
}
func (m *PGMD5HashResponse) XXX_Size() int {
	return xxx_messageInfo_PGMD5HashResponse.Size(m)
}
func (m *PGMD5HashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PGMD5HashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PGMD5HashResponse proto.InternalMessageInfo

func (m *PGMD5HashResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*PGMD5HashRequest)(nil), "dbauth.authenticator.protos.PGMD5HashRequest")
	proto.RegisterType((*PGMD5HashResponse)(nil), "dbauth.authenticator.protos.PGMD5HashResponse")
}

func init() { proto.RegisterFile("authenticator.proto", fileDescriptor_e86ec39f7c35dea3) }

var fileDescriptor_e86ec39f7c35dea3 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0xd6, 0x82, 0x4b, 0x8b, 0xba, 0x82, 0x86, 0x7a, 0x29, 0x39, 0x68, 0x2f, 0xe6,
	0xa0, 0x78, 0xf2, 0x54, 0x14, 0x62, 0x0f, 0x82, 0xe4, 0x0f, 0x84, 0x49, 0x76, 0xe8, 0x2e, 0x24,
	0xbb, 0x75, 0x67, 0x72, 0xf0, 0xe6, 0xff, 0xf2, 0xcf, 0x49, 0x36, 0x51, 0x8a, 0x88, 0xf4, 0x36,
	0xf3, 0xbe, 0xf7, 0xe0, 0xcd, 0x88, 0x33, 0x68, 0x59, 0xa3, 0x65, 0x53, 0x01, 0x3b, 0x9f, 0x6e,
	0xbc, 0x63, 0x27, 0x2f, 0x55, 0xd9, 0xc9, 0xe9, 0x1f, 0x8c, 0x92, 0xcf, 0x48, 0x9c, 0xbc, 0x66,
	0x2f, 0x4f, 0xf7, 0xcf, 0x40, 0x3a, 0xc7, 0xb7, 0x16, 0x89, 0xe5, 0x83, 0x98, 0x91, 0x59, 0x5b,
	0x54, 0xc5, 0x1a, 0xb9, 0xa8, 0xa0, 0xae, 0xd1, 0x17, 0x46, 0x75, 0x61, 0x7e, 0x8f, 0xa3, 0x79,
	0xb4, 0x38, 0xca, 0x2f, 0x7a, 0x47, 0x86, 0xfc, 0x18, 0xf8, 0x6a, 0xc0, 0xf2, 0x4a, 0x1c, 0x57,
	0x35, 0x98, 0x06, 0x55, 0x61, 0xa0, 0x29, 0xc0, 0xdb, 0x78, 0x3f, 0x24, 0xa6, 0x83, 0xbc, 0x82,
	0x66, 0xe9, 0xad, 0x3c, 0x17, 0x63, 0x55, 0x6a, 0x47, 0x1c, 0x1f, 0x04, 0x3c, 0x6c, 0xbd, 0xde,
	0x12, 0xfa, 0x78, 0xf4, 0xad, 0x77, 0x9b, 0x94, 0x62, 0x44, 0x50, 0x73, 0x7c, 0x38, 0x8f, 0x16,
	0x93, 0x3c, 0xcc, 0xc9, 0xb5, 0x38, 0xdd, 0x2a, 0x4f, 0x1b, 0x67, 0x09, 0x3b, 0xa3, 0x06, 0xd2,
	0x43, 0xcf, 0x30, 0xdf, 0x7e, 0x44, 0x62, 0xba, 0xdc, 0xbe, 0x5f, 0x3a, 0x31, 0xc9, 0x90, 0x7f,
	0xd2, 0xf2, 0x26, 0xfd, 0xe7, 0x4d, 0xe9, 0xef, 0x17, 0xcd, 0xd2, 0x5d, 0xed, 0x7d, 0xa9, 0x64,
	0xaf, 0x1c, 0x07, 0x76, 0xf7, 0x15, 0x00, 0x00, 0xff, 0xff, 0x10, 0xc4, 0xb4, 0x24, 0xa4, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthenticatorClient is the client API for Authenticator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticatorClient interface {
	GetPGMD5Hash(ctx context.Context, in *PGMD5HashRequest, opts ...grpc.CallOption) (*PGMD5HashResponse, error)
}

type authenticatorClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticatorClient(cc *grpc.ClientConn) AuthenticatorClient {
	return &authenticatorClient{cc}
}

func (c *authenticatorClient) GetPGMD5Hash(ctx context.Context, in *PGMD5HashRequest, opts ...grpc.CallOption) (*PGMD5HashResponse, error) {
	out := new(PGMD5HashResponse)
	err := c.cc.Invoke(ctx, "/dbauth.authenticator.protos.Authenticator/GetPGMD5Hash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticatorServer is the server API for Authenticator service.
type AuthenticatorServer interface {
	GetPGMD5Hash(context.Context, *PGMD5HashRequest) (*PGMD5HashResponse, error)
}

// UnimplementedAuthenticatorServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticatorServer struct {
}

func (*UnimplementedAuthenticatorServer) GetPGMD5Hash(ctx context.Context, req *PGMD5HashRequest) (*PGMD5HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPGMD5Hash not implemented")
}

func RegisterAuthenticatorServer(s *grpc.Server, srv AuthenticatorServer) {
	s.RegisterService(&_Authenticator_serviceDesc, srv)
}

func _Authenticator_GetPGMD5Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PGMD5HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).GetPGMD5Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbauth.authenticator.protos.Authenticator/GetPGMD5Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).GetPGMD5Hash(ctx, req.(*PGMD5HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authenticator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbauth.authenticator.protos.Authenticator",
	HandlerType: (*AuthenticatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPGMD5Hash",
			Handler:    _Authenticator_GetPGMD5Hash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authenticator.proto",
}
