# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authenticator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="authenticator.proto",
    package="approzium.authenticator.protos",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x13\x61uthenticator.proto\x12\x1e\x61pprozium.authenticator.protos"\x8d\x01\n\x10PGMD5HashRequest\x12"\n\x1asigned_get_caller_identity\x18\x01 \x01(\t\x12\x17\n\x0f\x63laimed_iam_arn\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x62host\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x62port\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x62user\x18\x05 \x01(\t\x12\x0c\n\x04salt\x18\x06 \x01(\x0c"\xc0\x01\n\x13PGSHA256HashRequest\x12"\n\x1asigned_get_caller_identity\x18\x01 \x01(\t\x12\x17\n\x0f\x63laimed_iam_arn\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x62host\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x62port\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x62user\x18\x05 \x01(\t\x12\x0c\n\x04salt\x18\x06 \x01(\t\x12\x12\n\niterations\x18\x07 \x01(\r\x12\x1a\n\x12\x61uthentication_msg\x18\x08 \x01(\t"\x1d\n\rPGMD5Response\x12\x0c\n\x04hash\x18\x01 \x01(\t"2\n\x10PGSHA256Response\x12\x0e\n\x06\x63proof\x18\x01 \x01(\t\x12\x0e\n\x06sproof\x18\x02 \x01(\t2\xfe\x01\n\rAuthenticator\x12q\n\x0cGetPGMD5Hash\x12\x30.approzium.authenticator.protos.PGMD5HashRequest\x1a-.approzium.authenticator.protos.PGMD5Response"\x00\x12z\n\x0fGetPGSHA256Hash\x12\x33.approzium.authenticator.protos.PGSHA256HashRequest\x1a\x30.approzium.authenticator.protos.PGSHA256Response"\x00\x62\x06proto3',
)


_PGMD5HASHREQUEST = _descriptor.Descriptor(
    name="PGMD5HashRequest",
    full_name="approzium.authenticator.protos.PGMD5HashRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="signed_get_caller_identity",
            full_name="approzium.authenticator.protos.PGMD5HashRequest.signed_get_caller_identity",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="claimed_iam_arn",
            full_name="approzium.authenticator.protos.PGMD5HashRequest.claimed_iam_arn",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="dbhost",
            full_name="approzium.authenticator.protos.PGMD5HashRequest.dbhost",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="dbport",
            full_name="approzium.authenticator.protos.PGMD5HashRequest.dbport",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="dbuser",
            full_name="approzium.authenticator.protos.PGMD5HashRequest.dbuser",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="salt",
            full_name="approzium.authenticator.protos.PGMD5HashRequest.salt",
            index=5,
            number=6,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=56,
    serialized_end=197,
)


_PGSHA256HASHREQUEST = _descriptor.Descriptor(
    name="PGSHA256HashRequest",
    full_name="approzium.authenticator.protos.PGSHA256HashRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="signed_get_caller_identity",
            full_name="approzium.authenticator.protos.PGSHA256HashRequest.signed_get_caller_identity",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="claimed_iam_arn",
            full_name="approzium.authenticator.protos.PGSHA256HashRequest.claimed_iam_arn",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="dbhost",
            full_name="approzium.authenticator.protos.PGSHA256HashRequest.dbhost",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="dbport",
            full_name="approzium.authenticator.protos.PGSHA256HashRequest.dbport",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="dbuser",
            full_name="approzium.authenticator.protos.PGSHA256HashRequest.dbuser",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="salt",
            full_name="approzium.authenticator.protos.PGSHA256HashRequest.salt",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="iterations",
            full_name="approzium.authenticator.protos.PGSHA256HashRequest.iterations",
            index=6,
            number=7,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="authentication_msg",
            full_name="approzium.authenticator.protos.PGSHA256HashRequest.authentication_msg",
            index=7,
            number=8,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=200,
    serialized_end=392,
)


_PGMD5RESPONSE = _descriptor.Descriptor(
    name="PGMD5Response",
    full_name="approzium.authenticator.protos.PGMD5Response",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="hash",
            full_name="approzium.authenticator.protos.PGMD5Response.hash",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=394,
    serialized_end=423,
)


_PGSHA256RESPONSE = _descriptor.Descriptor(
    name="PGSHA256Response",
    full_name="approzium.authenticator.protos.PGSHA256Response",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="cproof",
            full_name="approzium.authenticator.protos.PGSHA256Response.cproof",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="sproof",
            full_name="approzium.authenticator.protos.PGSHA256Response.sproof",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=425,
    serialized_end=475,
)

DESCRIPTOR.message_types_by_name["PGMD5HashRequest"] = _PGMD5HASHREQUEST
DESCRIPTOR.message_types_by_name["PGSHA256HashRequest"] = _PGSHA256HASHREQUEST
DESCRIPTOR.message_types_by_name["PGMD5Response"] = _PGMD5RESPONSE
DESCRIPTOR.message_types_by_name["PGSHA256Response"] = _PGSHA256RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PGMD5HashRequest = _reflection.GeneratedProtocolMessageType(
    "PGMD5HashRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _PGMD5HASHREQUEST,
        "__module__": "authenticator_pb2"
        # @@protoc_insertion_point(class_scope:approzium.authenticator.protos.PGMD5HashRequest)
    },
)
_sym_db.RegisterMessage(PGMD5HashRequest)

PGSHA256HashRequest = _reflection.GeneratedProtocolMessageType(
    "PGSHA256HashRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _PGSHA256HASHREQUEST,
        "__module__": "authenticator_pb2"
        # @@protoc_insertion_point(class_scope:approzium.authenticator.protos.PGSHA256HashRequest)
    },
)
_sym_db.RegisterMessage(PGSHA256HashRequest)

PGMD5Response = _reflection.GeneratedProtocolMessageType(
    "PGMD5Response",
    (_message.Message,),
    {
        "DESCRIPTOR": _PGMD5RESPONSE,
        "__module__": "authenticator_pb2"
        # @@protoc_insertion_point(class_scope:approzium.authenticator.protos.PGMD5Response)
    },
)
_sym_db.RegisterMessage(PGMD5Response)

PGSHA256Response = _reflection.GeneratedProtocolMessageType(
    "PGSHA256Response",
    (_message.Message,),
    {
        "DESCRIPTOR": _PGSHA256RESPONSE,
        "__module__": "authenticator_pb2"
        # @@protoc_insertion_point(class_scope:approzium.authenticator.protos.PGSHA256Response)
    },
)
_sym_db.RegisterMessage(PGSHA256Response)


_AUTHENTICATOR = _descriptor.ServiceDescriptor(
    name="Authenticator",
    full_name="approzium.authenticator.protos.Authenticator",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=478,
    serialized_end=732,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetPGMD5Hash",
            full_name="approzium.authenticator.protos.Authenticator.GetPGMD5Hash",
            index=0,
            containing_service=None,
            input_type=_PGMD5HASHREQUEST,
            output_type=_PGMD5RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="GetPGSHA256Hash",
            full_name="approzium.authenticator.protos.Authenticator.GetPGSHA256Hash",
            index=1,
            containing_service=None,
            input_type=_PGSHA256HASHREQUEST,
            output_type=_PGSHA256RESPONSE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_AUTHENTICATOR)

DESCRIPTOR.services_by_name["Authenticator"] = _AUTHENTICATOR

# @@protoc_insertion_point(module_scope)
