# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import authenticator_pb2 as authenticator__pb2


class AuthenticatorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPGMD5Hash = channel.unary_unary(
                '/dbauth.authenticator.protos.Authenticator/GetPGMD5Hash',
                request_serializer=authenticator__pb2.PGMD5HashRequest.SerializeToString,
                response_deserializer=authenticator__pb2.PGMD5HashResponse.FromString,
                )


class AuthenticatorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetPGMD5Hash(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPGMD5Hash': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPGMD5Hash,
                    request_deserializer=authenticator__pb2.PGMD5HashRequest.FromString,
                    response_serializer=authenticator__pb2.PGMD5HashResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbauth.authenticator.protos.Authenticator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Authenticator(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetPGMD5Hash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbauth.authenticator.protos.Authenticator/GetPGMD5Hash',
            authenticator__pb2.PGMD5HashRequest.SerializeToString,
            authenticator__pb2.PGMD5HashResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
