// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authenticator.proto

package approzium_authenticator_protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientLanguage int32

const (
	ClientLanguage_LANGUAGE_NOT_PROVIDED ClientLanguage = 0
	ClientLanguage_PYTHON                ClientLanguage = 1
	ClientLanguage_GO                    ClientLanguage = 2
)

var ClientLanguage_name = map[int32]string{
	0: "LANGUAGE_NOT_PROVIDED",
	1: "PYTHON",
	2: "GO",
}

var ClientLanguage_value = map[string]int32{
	"LANGUAGE_NOT_PROVIDED": 0,
	"PYTHON":                1,
	"GO":                    2,
}

func (x ClientLanguage) String() string {
	return proto.EnumName(ClientLanguage_name, int32(x))
}

func (ClientLanguage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{0}
}

type AWSIdentity struct {
	SignedGetCallerIdentity string   `protobuf:"bytes,1,opt,name=signed_get_caller_identity,json=signedGetCallerIdentity,proto3" json:"signed_get_caller_identity,omitempty"`
	ClaimedIamArn           string   `protobuf:"bytes,2,opt,name=claimed_iam_arn,json=claimedIamArn,proto3" json:"claimed_iam_arn,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *AWSIdentity) Reset()         { *m = AWSIdentity{} }
func (m *AWSIdentity) String() string { return proto.CompactTextString(m) }
func (*AWSIdentity) ProtoMessage()    {}
func (*AWSIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{0}
}

func (m *AWSIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSIdentity.Unmarshal(m, b)
}
func (m *AWSIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSIdentity.Marshal(b, m, deterministic)
}
func (m *AWSIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSIdentity.Merge(m, src)
}
func (m *AWSIdentity) XXX_Size() int {
	return xxx_messageInfo_AWSIdentity.Size(m)
}
func (m *AWSIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_AWSIdentity proto.InternalMessageInfo

func (m *AWSIdentity) GetSignedGetCallerIdentity() string {
	if m != nil {
		return m.SignedGetCallerIdentity
	}
	return ""
}

func (m *AWSIdentity) GetClaimedIamArn() string {
	if m != nil {
		return m.ClaimedIamArn
	}
	return ""
}

type PasswordRequest struct {
	ClientLanguage ClientLanguage `protobuf:"varint,1,opt,name=client_language,json=clientLanguage,proto3,enum=approzium.authenticator.protos.ClientLanguage" json:"client_language,omitempty"`
	Dbhost         string         `protobuf:"bytes,2,opt,name=dbhost,proto3" json:"dbhost,omitempty"`
	Dbport         string         `protobuf:"bytes,3,opt,name=dbport,proto3" json:"dbport,omitempty"`
	Dbuser         string         `protobuf:"bytes,4,opt,name=dbuser,proto3" json:"dbuser,omitempty"`
	// Types that are valid to be assigned to Identity:
	//	*PasswordRequest_Aws
	Identity             isPasswordRequest_Identity `protobuf_oneof:"identity"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PasswordRequest) Reset()         { *m = PasswordRequest{} }
func (m *PasswordRequest) String() string { return proto.CompactTextString(m) }
func (*PasswordRequest) ProtoMessage()    {}
func (*PasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{1}
}

func (m *PasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordRequest.Unmarshal(m, b)
}
func (m *PasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordRequest.Marshal(b, m, deterministic)
}
func (m *PasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordRequest.Merge(m, src)
}
func (m *PasswordRequest) XXX_Size() int {
	return xxx_messageInfo_PasswordRequest.Size(m)
}
func (m *PasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordRequest proto.InternalMessageInfo

func (m *PasswordRequest) GetClientLanguage() ClientLanguage {
	if m != nil {
		return m.ClientLanguage
	}
	return ClientLanguage_LANGUAGE_NOT_PROVIDED
}

func (m *PasswordRequest) GetDbhost() string {
	if m != nil {
		return m.Dbhost
	}
	return ""
}

func (m *PasswordRequest) GetDbport() string {
	if m != nil {
		return m.Dbport
	}
	return ""
}

func (m *PasswordRequest) GetDbuser() string {
	if m != nil {
		return m.Dbuser
	}
	return ""
}

type isPasswordRequest_Identity interface {
	isPasswordRequest_Identity()
}

type PasswordRequest_Aws struct {
	Aws *AWSIdentity `protobuf:"bytes,5,opt,name=aws,proto3,oneof"`
}

func (*PasswordRequest_Aws) isPasswordRequest_Identity() {}

func (m *PasswordRequest) GetIdentity() isPasswordRequest_Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *PasswordRequest) GetAws() *AWSIdentity {
	if x, ok := m.GetIdentity().(*PasswordRequest_Aws); ok {
		return x.Aws
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PasswordRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PasswordRequest_Aws)(nil),
	}
}

type PGMD5HashRequest struct {
	PwdRequest           *PasswordRequest `protobuf:"bytes,1,opt,name=pwd_request,json=pwdRequest,proto3" json:"pwd_request,omitempty"`
	Salt                 []byte           `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PGMD5HashRequest) Reset()         { *m = PGMD5HashRequest{} }
func (m *PGMD5HashRequest) String() string { return proto.CompactTextString(m) }
func (*PGMD5HashRequest) ProtoMessage()    {}
func (*PGMD5HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{2}
}

func (m *PGMD5HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGMD5HashRequest.Unmarshal(m, b)
}
func (m *PGMD5HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGMD5HashRequest.Marshal(b, m, deterministic)
}
func (m *PGMD5HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGMD5HashRequest.Merge(m, src)
}
func (m *PGMD5HashRequest) XXX_Size() int {
	return xxx_messageInfo_PGMD5HashRequest.Size(m)
}
func (m *PGMD5HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PGMD5HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PGMD5HashRequest proto.InternalMessageInfo

func (m *PGMD5HashRequest) GetPwdRequest() *PasswordRequest {
	if m != nil {
		return m.PwdRequest
	}
	return nil
}

func (m *PGMD5HashRequest) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type PGMD5Response struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PGMD5Response) Reset()         { *m = PGMD5Response{} }
func (m *PGMD5Response) String() string { return proto.CompactTextString(m) }
func (*PGMD5Response) ProtoMessage()    {}
func (*PGMD5Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{3}
}

func (m *PGMD5Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGMD5Response.Unmarshal(m, b)
}
func (m *PGMD5Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGMD5Response.Marshal(b, m, deterministic)
}
func (m *PGMD5Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGMD5Response.Merge(m, src)
}
func (m *PGMD5Response) XXX_Size() int {
	return xxx_messageInfo_PGMD5Response.Size(m)
}
func (m *PGMD5Response) XXX_DiscardUnknown() {
	xxx_messageInfo_PGMD5Response.DiscardUnknown(m)
}

var xxx_messageInfo_PGMD5Response proto.InternalMessageInfo

func (m *PGMD5Response) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type PGSHA256HashRequest struct {
	PwdRequest           *PasswordRequest `protobuf:"bytes,1,opt,name=pwd_request,json=pwdRequest,proto3" json:"pwd_request,omitempty"`
	Salt                 string           `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Iterations           uint32           `protobuf:"varint,3,opt,name=iterations,proto3" json:"iterations,omitempty"`
	AuthenticationMsg    string           `protobuf:"bytes,4,opt,name=authentication_msg,json=authenticationMsg,proto3" json:"authentication_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PGSHA256HashRequest) Reset()         { *m = PGSHA256HashRequest{} }
func (m *PGSHA256HashRequest) String() string { return proto.CompactTextString(m) }
func (*PGSHA256HashRequest) ProtoMessage()    {}
func (*PGSHA256HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{4}
}

func (m *PGSHA256HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGSHA256HashRequest.Unmarshal(m, b)
}
func (m *PGSHA256HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGSHA256HashRequest.Marshal(b, m, deterministic)
}
func (m *PGSHA256HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGSHA256HashRequest.Merge(m, src)
}
func (m *PGSHA256HashRequest) XXX_Size() int {
	return xxx_messageInfo_PGSHA256HashRequest.Size(m)
}
func (m *PGSHA256HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PGSHA256HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PGSHA256HashRequest proto.InternalMessageInfo

func (m *PGSHA256HashRequest) GetPwdRequest() *PasswordRequest {
	if m != nil {
		return m.PwdRequest
	}
	return nil
}

func (m *PGSHA256HashRequest) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *PGSHA256HashRequest) GetIterations() uint32 {
	if m != nil {
		return m.Iterations
	}
	return 0
}

func (m *PGSHA256HashRequest) GetAuthenticationMsg() string {
	if m != nil {
		return m.AuthenticationMsg
	}
	return ""
}

type PGSHA256Response struct {
	Cproof               string   `protobuf:"bytes,1,opt,name=cproof,proto3" json:"cproof,omitempty"`
	Sproof               string   `protobuf:"bytes,2,opt,name=sproof,proto3" json:"sproof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PGSHA256Response) Reset()         { *m = PGSHA256Response{} }
func (m *PGSHA256Response) String() string { return proto.CompactTextString(m) }
func (*PGSHA256Response) ProtoMessage()    {}
func (*PGSHA256Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{5}
}

func (m *PGSHA256Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGSHA256Response.Unmarshal(m, b)
}
func (m *PGSHA256Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGSHA256Response.Marshal(b, m, deterministic)
}
func (m *PGSHA256Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGSHA256Response.Merge(m, src)
}
func (m *PGSHA256Response) XXX_Size() int {
	return xxx_messageInfo_PGSHA256Response.Size(m)
}
func (m *PGSHA256Response) XXX_DiscardUnknown() {
	xxx_messageInfo_PGSHA256Response.DiscardUnknown(m)
}

var xxx_messageInfo_PGSHA256Response proto.InternalMessageInfo

func (m *PGSHA256Response) GetCproof() string {
	if m != nil {
		return m.Cproof
	}
	return ""
}

func (m *PGSHA256Response) GetSproof() string {
	if m != nil {
		return m.Sproof
	}
	return ""
}

type MYSQLSHA1HashRequest struct {
	PwdRequest           *PasswordRequest `protobuf:"bytes,1,opt,name=pwd_request,json=pwdRequest,proto3" json:"pwd_request,omitempty"`
	Salt                 []byte           `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MYSQLSHA1HashRequest) Reset()         { *m = MYSQLSHA1HashRequest{} }
func (m *MYSQLSHA1HashRequest) String() string { return proto.CompactTextString(m) }
func (*MYSQLSHA1HashRequest) ProtoMessage()    {}
func (*MYSQLSHA1HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{6}
}

func (m *MYSQLSHA1HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MYSQLSHA1HashRequest.Unmarshal(m, b)
}
func (m *MYSQLSHA1HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MYSQLSHA1HashRequest.Marshal(b, m, deterministic)
}
func (m *MYSQLSHA1HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MYSQLSHA1HashRequest.Merge(m, src)
}
func (m *MYSQLSHA1HashRequest) XXX_Size() int {
	return xxx_messageInfo_MYSQLSHA1HashRequest.Size(m)
}
func (m *MYSQLSHA1HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MYSQLSHA1HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MYSQLSHA1HashRequest proto.InternalMessageInfo

func (m *MYSQLSHA1HashRequest) GetPwdRequest() *PasswordRequest {
	if m != nil {
		return m.PwdRequest
	}
	return nil
}

func (m *MYSQLSHA1HashRequest) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type MYSQLSHA1Response struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MYSQLSHA1Response) Reset()         { *m = MYSQLSHA1Response{} }
func (m *MYSQLSHA1Response) String() string { return proto.CompactTextString(m) }
func (*MYSQLSHA1Response) ProtoMessage()    {}
func (*MYSQLSHA1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{7}
}

func (m *MYSQLSHA1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MYSQLSHA1Response.Unmarshal(m, b)
}
func (m *MYSQLSHA1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MYSQLSHA1Response.Marshal(b, m, deterministic)
}
func (m *MYSQLSHA1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MYSQLSHA1Response.Merge(m, src)
}
func (m *MYSQLSHA1Response) XXX_Size() int {
	return xxx_messageInfo_MYSQLSHA1Response.Size(m)
}
func (m *MYSQLSHA1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_MYSQLSHA1Response.DiscardUnknown(m)
}

var xxx_messageInfo_MYSQLSHA1Response proto.InternalMessageInfo

func (m *MYSQLSHA1Response) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterEnum("approzium.authenticator.protos.ClientLanguage", ClientLanguage_name, ClientLanguage_value)
	proto.RegisterType((*AWSIdentity)(nil), "approzium.authenticator.protos.AWSIdentity")
	proto.RegisterType((*PasswordRequest)(nil), "approzium.authenticator.protos.PasswordRequest")
	proto.RegisterType((*PGMD5HashRequest)(nil), "approzium.authenticator.protos.PGMD5HashRequest")
	proto.RegisterType((*PGMD5Response)(nil), "approzium.authenticator.protos.PGMD5Response")
	proto.RegisterType((*PGSHA256HashRequest)(nil), "approzium.authenticator.protos.PGSHA256HashRequest")
	proto.RegisterType((*PGSHA256Response)(nil), "approzium.authenticator.protos.PGSHA256Response")
	proto.RegisterType((*MYSQLSHA1HashRequest)(nil), "approzium.authenticator.protos.MYSQLSHA1HashRequest")
	proto.RegisterType((*MYSQLSHA1Response)(nil), "approzium.authenticator.protos.MYSQLSHA1Response")
}

func init() { proto.RegisterFile("authenticator.proto", fileDescriptor_e86ec39f7c35dea3) }

var fileDescriptor_e86ec39f7c35dea3 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xd3, 0x12, 0xd1, 0xc9, 0x67, 0xb7, 0x50, 0x42, 0x0e, 0x55, 0x65, 0x24, 0xa8, 0x40,
	0x0d, 0x6d, 0x4a, 0xb9, 0x70, 0xa8, 0xdc, 0xa6, 0x72, 0x22, 0xe5, 0xc3, 0x38, 0x85, 0xaa, 0x27,
	0x6b, 0x1b, 0x2f, 0x8e, 0xa5, 0xc4, 0xeb, 0xee, 0x6e, 0x14, 0xa8, 0xe0, 0x0f, 0xf2, 0x9f, 0x10,
	0xc8, 0xeb, 0x4d, 0x9a, 0x94, 0xa8, 0xce, 0xa9, 0x37, 0xcf, 0x1b, 0x3f, 0xbf, 0x79, 0xf3, 0xc6,
	0xb0, 0x85, 0xc7, 0x62, 0x40, 0x02, 0xe1, 0xf7, 0xb1, 0xa0, 0xac, 0x1a, 0x32, 0x2a, 0x28, 0xda,
	0xc1, 0x61, 0xc8, 0xe8, 0xad, 0x3f, 0x1e, 0x55, 0x97, 0xb4, 0xb9, 0xce, 0x20, 0x6b, 0x5c, 0xf6,
	0x9a, 0x6e, 0xd4, 0x10, 0x3f, 0xd0, 0x27, 0xa8, 0x70, 0xdf, 0x0b, 0x88, 0xeb, 0x78, 0x44, 0x38,
	0x7d, 0x3c, 0x1c, 0x12, 0xe6, 0xf8, 0xaa, 0x5b, 0xd6, 0x76, 0xb5, 0xbd, 0x0d, 0xfb, 0x45, 0xfc,
	0x86, 0x49, 0xc4, 0x99, 0xec, 0xcf, 0xc8, 0xaf, 0xa1, 0xd8, 0x1f, 0x62, 0x7f, 0x44, 0x5c, 0xc7,
	0xc7, 0x23, 0x07, 0xb3, 0xa0, 0x9c, 0x96, 0x8c, 0xbc, 0x82, 0x9b, 0x78, 0x64, 0xb0, 0x40, 0xff,
	0xab, 0x41, 0xd1, 0xc2, 0x9c, 0x4f, 0x28, 0x73, 0x6d, 0x72, 0x33, 0x26, 0x5c, 0xa0, 0xcb, 0x88,
	0xeb, 0x93, 0x40, 0x38, 0x43, 0x1c, 0x78, 0x63, 0xec, 0x11, 0xa9, 0x56, 0xa8, 0x55, 0xab, 0x0f,
	0x3b, 0xa8, 0x9e, 0x49, 0x5a, 0x4b, 0xb1, 0xec, 0x42, 0x7f, 0xa1, 0x46, 0xdb, 0x90, 0x71, 0xaf,
	0x07, 0x94, 0x0b, 0x35, 0x8b, 0xaa, 0x62, 0x3c, 0xa4, 0x4c, 0x94, 0xd7, 0xa6, 0x78, 0x54, 0xc5,
	0xf8, 0x98, 0x13, 0x56, 0x5e, 0x9f, 0xe2, 0x51, 0x85, 0x4e, 0x60, 0x0d, 0x4f, 0x78, 0xf9, 0xc9,
	0xae, 0xb6, 0x97, 0xad, 0xbd, 0x4b, 0x1a, 0x6a, 0x6e, 0xa7, 0x8d, 0x94, 0x1d, 0x31, 0x4f, 0x01,
	0x9e, 0x4e, 0x17, 0xa9, 0x7f, 0x87, 0x92, 0x65, 0xb6, 0xeb, 0xc7, 0x0d, 0xcc, 0x07, 0xd3, 0x0d,
	0x58, 0x90, 0x0d, 0x27, 0xae, 0xc3, 0xe2, 0x52, 0xba, 0xcf, 0xd6, 0xde, 0x27, 0x09, 0xdd, 0xdb,
	0xa3, 0x0d, 0xe1, 0x64, 0xb6, 0x53, 0x04, 0xeb, 0x1c, 0x0f, 0x63, 0xe3, 0x39, 0x5b, 0x3e, 0xeb,
	0xaf, 0x20, 0x2f, 0x95, 0x6d, 0xc2, 0x43, 0x1a, 0x70, 0x12, 0xbd, 0x34, 0xc0, 0x7c, 0xa0, 0xb2,
	0x95, 0xcf, 0xfa, 0x6f, 0x0d, 0xb6, 0x2c, 0xb3, 0xd7, 0x30, 0x6a, 0xc7, 0x1f, 0x1f, 0x6f, 0xc4,
	0x8d, 0x78, 0x44, 0xb4, 0x03, 0xe0, 0x0b, 0xc2, 0xb0, 0xf0, 0x69, 0xc0, 0x65, 0x3a, 0x79, 0x7b,
	0x0e, 0x41, 0xfb, 0x80, 0xe6, 0x74, 0x7c, 0x1a, 0x38, 0x23, 0xee, 0xa9, 0xb4, 0x36, 0x17, 0x3b,
	0x6d, 0xee, 0xe9, 0xa7, 0xd1, 0xae, 0x63, 0x2f, 0x33, 0xd3, 0xdb, 0x90, 0xe9, 0x87, 0x8c, 0xd2,
	0x6f, 0xca, 0xb6, 0xaa, 0x22, 0x9c, 0xc7, 0xb8, 0x3a, 0x96, 0xb8, 0xd2, 0x7f, 0xc2, 0xb3, 0xf6,
	0x55, 0xef, 0x73, 0xab, 0xd7, 0x30, 0x0e, 0x1f, 0x3f, 0xb3, 0x37, 0xb0, 0x39, 0x53, 0x5f, 0x9a,
	0x5b, 0x2e, 0xce, 0xed, 0xed, 0x09, 0x14, 0x16, 0xff, 0x06, 0xf4, 0x12, 0x9e, 0xb7, 0x8c, 0x8e,
	0xf9, 0xc5, 0x30, 0xcf, 0x9d, 0x4e, 0xf7, 0xc2, 0xb1, 0xec, 0xee, 0xd7, 0x66, 0xfd, 0xbc, 0x5e,
	0x4a, 0x21, 0x80, 0x8c, 0x75, 0x75, 0xd1, 0xe8, 0x76, 0x4a, 0x1a, 0xca, 0x40, 0xda, 0xec, 0x96,
	0xd2, 0xb5, 0x3f, 0x69, 0xc8, 0x1b, 0xf3, 0x23, 0xa3, 0x1b, 0xc8, 0x99, 0x44, 0xcc, 0x8e, 0x15,
	0x1d, 0x24, 0x9a, 0xbb, 0x77, 0xd7, 0x95, 0xfd, 0x95, 0x18, 0x53, 0x5f, 0x7a, 0x0a, 0xdd, 0x42,
	0x51, 0x4a, 0xde, 0xdd, 0x1f, 0x3a, 0x4a, 0xfe, 0xc6, 0x7f, 0xd7, 0x5a, 0x39, 0x58, 0x95, 0x34,
	0xa7, 0xfd, 0x0b, 0x4a, 0x26, 0x11, 0x0b, 0x59, 0xa3, 0x0f, 0x49, 0xdf, 0x59, 0x76, 0x1a, 0x95,
	0xc3, 0x95, 0x59, 0x77, 0xf2, 0xd7, 0x19, 0xd9, 0x3b, 0xfa, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0x55, 0x94, 0x8b, 0xcb, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticatorClient is the client API for Authenticator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticatorClient interface {
	GetPGMD5Hash(ctx context.Context, in *PGMD5HashRequest, opts ...grpc.CallOption) (*PGMD5Response, error)
	GetPGSHA256Hash(ctx context.Context, in *PGSHA256HashRequest, opts ...grpc.CallOption) (*PGSHA256Response, error)
	GetMYSQLSHA1Hash(ctx context.Context, in *MYSQLSHA1HashRequest, opts ...grpc.CallOption) (*MYSQLSHA1Response, error)
}

type authenticatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticatorClient(cc grpc.ClientConnInterface) AuthenticatorClient {
	return &authenticatorClient{cc}
}

func (c *authenticatorClient) GetPGMD5Hash(ctx context.Context, in *PGMD5HashRequest, opts ...grpc.CallOption) (*PGMD5Response, error) {
	out := new(PGMD5Response)
	err := c.cc.Invoke(ctx, "/approzium.authenticator.protos.Authenticator/GetPGMD5Hash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticatorClient) GetPGSHA256Hash(ctx context.Context, in *PGSHA256HashRequest, opts ...grpc.CallOption) (*PGSHA256Response, error) {
	out := new(PGSHA256Response)
	err := c.cc.Invoke(ctx, "/approzium.authenticator.protos.Authenticator/GetPGSHA256Hash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticatorClient) GetMYSQLSHA1Hash(ctx context.Context, in *MYSQLSHA1HashRequest, opts ...grpc.CallOption) (*MYSQLSHA1Response, error) {
	out := new(MYSQLSHA1Response)
	err := c.cc.Invoke(ctx, "/approzium.authenticator.protos.Authenticator/GetMYSQLSHA1Hash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticatorServer is the server API for Authenticator service.
type AuthenticatorServer interface {
	GetPGMD5Hash(context.Context, *PGMD5HashRequest) (*PGMD5Response, error)
	GetPGSHA256Hash(context.Context, *PGSHA256HashRequest) (*PGSHA256Response, error)
	GetMYSQLSHA1Hash(context.Context, *MYSQLSHA1HashRequest) (*MYSQLSHA1Response, error)
}

// UnimplementedAuthenticatorServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticatorServer struct {
}

func (*UnimplementedAuthenticatorServer) GetPGMD5Hash(ctx context.Context, req *PGMD5HashRequest) (*PGMD5Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPGMD5Hash not implemented")
}
func (*UnimplementedAuthenticatorServer) GetPGSHA256Hash(ctx context.Context, req *PGSHA256HashRequest) (*PGSHA256Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPGSHA256Hash not implemented")
}
func (*UnimplementedAuthenticatorServer) GetMYSQLSHA1Hash(ctx context.Context, req *MYSQLSHA1HashRequest) (*MYSQLSHA1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMYSQLSHA1Hash not implemented")
}

func RegisterAuthenticatorServer(s *grpc.Server, srv AuthenticatorServer) {
	s.RegisterService(&_Authenticator_serviceDesc, srv)
}

func _Authenticator_GetPGMD5Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PGMD5HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).GetPGMD5Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/approzium.authenticator.protos.Authenticator/GetPGMD5Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).GetPGMD5Hash(ctx, req.(*PGMD5HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticator_GetPGSHA256Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PGSHA256HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).GetPGSHA256Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/approzium.authenticator.protos.Authenticator/GetPGSHA256Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).GetPGSHA256Hash(ctx, req.(*PGSHA256HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticator_GetMYSQLSHA1Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MYSQLSHA1HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).GetMYSQLSHA1Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/approzium.authenticator.protos.Authenticator/GetMYSQLSHA1Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).GetMYSQLSHA1Hash(ctx, req.(*MYSQLSHA1HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authenticator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "approzium.authenticator.protos.Authenticator",
	HandlerType: (*AuthenticatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPGMD5Hash",
			Handler:    _Authenticator_GetPGMD5Hash_Handler,
		},
		{
			MethodName: "GetPGSHA256Hash",
			Handler:    _Authenticator_GetPGSHA256Hash_Handler,
		},
		{
			MethodName: "GetMYSQLSHA1Hash",
			Handler:    _Authenticator_GetMYSQLSHA1Hash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authenticator.proto",
}
