name: Reusable Docs Build
on:
  workflow_call:
    
jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: docs/yarn.lock
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
          dir: docs
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: docs
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './docs/build'
