// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authenticator.proto

package dbauth_authenticator_messages

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticateResponse_Status int32

const (
	AuthenticateResponse_ERROR   AuthenticateResponse_Status = 0
	AuthenticateResponse_SUCCESS AuthenticateResponse_Status = 1
)

var AuthenticateResponse_Status_name = map[int32]string{
	0: "ERROR",
	1: "SUCCESS",
}

var AuthenticateResponse_Status_value = map[string]int32{
	"ERROR":   0,
	"SUCCESS": 1,
}

func (x AuthenticateResponse_Status) String() string {
	return proto.EnumName(AuthenticateResponse_Status_name, int32(x))
}

func (AuthenticateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{2, 0}
}

type Credentials struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	HashedPassword       string   `protobuf:"bytes,2,opt,name=hashedPassword,proto3" json:"hashedPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{0}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Credentials) GetHashedPassword() string {
	if m != nil {
		return m.HashedPassword
	}
	return ""
}

type AuthenticateRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Salt                 string   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{1}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *AuthenticateRequest) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

type AuthenticateResponse struct {
	Status               AuthenticateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=dbauth.authenticator.messages.AuthenticateResponse_Status" json:"status,omitempty"`
	Message              string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Credentials          *Credentials                `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86ec39f7c35dea3, []int{2}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetStatus() AuthenticateResponse_Status {
	if m != nil {
		return m.Status
	}
	return AuthenticateResponse_ERROR
}

func (m *AuthenticateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AuthenticateResponse) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func init() {
	proto.RegisterEnum("dbauth.authenticator.messages.AuthenticateResponse_Status", AuthenticateResponse_Status_name, AuthenticateResponse_Status_value)
	proto.RegisterType((*Credentials)(nil), "dbauth.authenticator.messages.Credentials")
	proto.RegisterType((*AuthenticateRequest)(nil), "dbauth.authenticator.messages.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "dbauth.authenticator.messages.AuthenticateResponse")
}

func init() { proto.RegisterFile("authenticator.proto", fileDescriptor_e86ec39f7c35dea3) }

var fileDescriptor_e86ec39f7c35dea3 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x3b, 0xfe, 0xa4, 0xf6, 0x46, 0x4b, 0xb9, 0x75, 0x11, 0x0a, 0x42, 0xc8, 0x42, 0x8a,
	0x8b, 0x2c, 0xd2, 0x9d, 0xbb, 0x12, 0xb2, 0x10, 0x04, 0x65, 0x82, 0x0f, 0x30, 0x6d, 0x2e, 0xa6,
	0x50, 0x9b, 0x3a, 0x77, 0x82, 0xf4, 0x15, 0x7c, 0x5e, 0x1f, 0x40, 0x32, 0x8e, 0x36, 0x15, 0x51,
	0xec, 0xee, 0xfe, 0xcc, 0x7c, 0x67, 0xce, 0x61, 0x60, 0xa8, 0x6a, 0x53, 0xd2, 0xca, 0x2c, 0xe6,
	0xca, 0x54, 0x3a, 0x5e, 0xeb, 0xca, 0x54, 0x78, 0x51, 0xcc, 0x9a, 0x71, 0xbc, 0xbb, 0x7b, 0x22,
	0x66, 0xf5, 0x48, 0x1c, 0xdd, 0x80, 0x9f, 0x6a, 0x2a, 0x9a, 0x8d, 0x5a, 0x32, 0x22, 0x1c, 0xd5,
	0x4c, 0x3a, 0x10, 0xa1, 0x18, 0xf7, 0xa4, 0xad, 0xf1, 0x12, 0xfa, 0xa5, 0xe2, 0x92, 0x8a, 0x7b,
	0xc5, 0xfc, 0x52, 0xe9, 0x22, 0x38, 0xb0, 0xdb, 0x6f, 0xd3, 0x28, 0x83, 0xe1, 0x74, 0x2b, 0x42,
	0x92, 0x9e, 0x6b, 0x62, 0x83, 0x23, 0x38, 0x59, 0x58, 0xbe, 0xd9, 0x38, 0xec, 0x57, 0xdf, 0xc8,
	0xb1, 0x5a, 0x1a, 0x07, 0xb4, 0x75, 0xf4, 0x26, 0xe0, 0x7c, 0x97, 0xc3, 0xeb, 0x6a, 0xc5, 0x84,
	0x12, 0x3c, 0x36, 0xca, 0xd4, 0x6c, 0x31, 0xfd, 0xe4, 0x3a, 0xfe, 0xd5, 0x5a, 0xfc, 0x13, 0x24,
	0xce, 0x2d, 0x41, 0x3a, 0x12, 0x06, 0xd0, 0x75, 0xe7, 0xdd, 0x1b, 0x3e, 0x5b, 0xbc, 0x05, 0x7f,
	0xbe, 0x0d, 0x26, 0x38, 0x0c, 0xc5, 0xd8, 0x4f, 0xae, 0xfe, 0x90, 0x6c, 0x45, 0x29, 0xdb, 0xd7,
	0xa3, 0x10, 0xbc, 0x0f, 0x65, 0xec, 0xc1, 0x71, 0x26, 0xe5, 0x9d, 0x1c, 0x74, 0xd0, 0x87, 0x6e,
	0xfe, 0x90, 0xa6, 0x59, 0x9e, 0x0f, 0x44, 0xf2, 0x2a, 0xe0, 0x6c, 0xda, 0xa6, 0xe2, 0x06, 0x4e,
	0xdb, 0x16, 0x30, 0xf9, 0x97, 0x5f, 0x1b, 0xfe, 0x68, 0xb2, 0x47, 0x46, 0x51, 0x67, 0xe6, 0xd9,
	0xbf, 0x33, 0x79, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x63, 0x12, 0x85, 0x52, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthenticatorClient is the client API for Authenticator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticatorClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type authenticatorClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticatorClient(cc *grpc.ClientConn) AuthenticatorClient {
	return &authenticatorClient{cc}
}

func (c *authenticatorClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/dbauth.authenticator.messages.Authenticator/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticatorServer is the server API for Authenticator service.
type AuthenticatorServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
}

// UnimplementedAuthenticatorServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticatorServer struct {
}

func (*UnimplementedAuthenticatorServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}

func RegisterAuthenticatorServer(s *grpc.Server, srv AuthenticatorServer) {
	s.RegisterService(&_Authenticator_serviceDesc, srv)
}

func _Authenticator_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbauth.authenticator.messages.Authenticator/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authenticator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbauth.authenticator.messages.Authenticator",
	HandlerType: (*AuthenticatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _Authenticator_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authenticator.proto",
}
