/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: authenticator/messages/authenticator.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "authenticator/messages/authenticator.pb-c.h"
void   dbauth__authenticator__messages__credentials__init
                     (Dbauth__Authenticator__Messages__Credentials         *message)
{
  static const Dbauth__Authenticator__Messages__Credentials init_value = DBAUTH__AUTHENTICATOR__MESSAGES__CREDENTIALS__INIT;
  *message = init_value;
}
size_t dbauth__authenticator__messages__credentials__get_packed_size
                     (const Dbauth__Authenticator__Messages__Credentials *message)
{
  assert(message->base.descriptor == &dbauth__authenticator__messages__credentials__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbauth__authenticator__messages__credentials__pack
                     (const Dbauth__Authenticator__Messages__Credentials *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbauth__authenticator__messages__credentials__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbauth__authenticator__messages__credentials__pack_to_buffer
                     (const Dbauth__Authenticator__Messages__Credentials *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbauth__authenticator__messages__credentials__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbauth__Authenticator__Messages__Credentials *
       dbauth__authenticator__messages__credentials__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbauth__Authenticator__Messages__Credentials *)
     protobuf_c_message_unpack (&dbauth__authenticator__messages__credentials__descriptor,
                                allocator, len, data);
}
void   dbauth__authenticator__messages__credentials__free_unpacked
                     (Dbauth__Authenticator__Messages__Credentials *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbauth__authenticator__messages__credentials__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbauth__authenticator__messages__authenticate_request__init
                     (Dbauth__Authenticator__Messages__AuthenticateRequest         *message)
{
  static const Dbauth__Authenticator__Messages__AuthenticateRequest init_value = DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_REQUEST__INIT;
  *message = init_value;
}
size_t dbauth__authenticator__messages__authenticate_request__get_packed_size
                     (const Dbauth__Authenticator__Messages__AuthenticateRequest *message)
{
  assert(message->base.descriptor == &dbauth__authenticator__messages__authenticate_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbauth__authenticator__messages__authenticate_request__pack
                     (const Dbauth__Authenticator__Messages__AuthenticateRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbauth__authenticator__messages__authenticate_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbauth__authenticator__messages__authenticate_request__pack_to_buffer
                     (const Dbauth__Authenticator__Messages__AuthenticateRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbauth__authenticator__messages__authenticate_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbauth__Authenticator__Messages__AuthenticateRequest *
       dbauth__authenticator__messages__authenticate_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbauth__Authenticator__Messages__AuthenticateRequest *)
     protobuf_c_message_unpack (&dbauth__authenticator__messages__authenticate_request__descriptor,
                                allocator, len, data);
}
void   dbauth__authenticator__messages__authenticate_request__free_unpacked
                     (Dbauth__Authenticator__Messages__AuthenticateRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbauth__authenticator__messages__authenticate_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbauth__authenticator__messages__authenticate_response__init
                     (Dbauth__Authenticator__Messages__AuthenticateResponse         *message)
{
  static const Dbauth__Authenticator__Messages__AuthenticateResponse init_value = DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_RESPONSE__INIT;
  *message = init_value;
}
size_t dbauth__authenticator__messages__authenticate_response__get_packed_size
                     (const Dbauth__Authenticator__Messages__AuthenticateResponse *message)
{
  assert(message->base.descriptor == &dbauth__authenticator__messages__authenticate_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbauth__authenticator__messages__authenticate_response__pack
                     (const Dbauth__Authenticator__Messages__AuthenticateResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbauth__authenticator__messages__authenticate_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbauth__authenticator__messages__authenticate_response__pack_to_buffer
                     (const Dbauth__Authenticator__Messages__AuthenticateResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbauth__authenticator__messages__authenticate_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbauth__Authenticator__Messages__AuthenticateResponse *
       dbauth__authenticator__messages__authenticate_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbauth__Authenticator__Messages__AuthenticateResponse *)
     protobuf_c_message_unpack (&dbauth__authenticator__messages__authenticate_response__descriptor,
                                allocator, len, data);
}
void   dbauth__authenticator__messages__authenticate_response__free_unpacked
                     (Dbauth__Authenticator__Messages__AuthenticateResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbauth__authenticator__messages__authenticate_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dbauth__authenticator__messages__credentials__field_descriptors[2] =
{
  {
    "user",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbauth__Authenticator__Messages__Credentials, user),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbauth__Authenticator__Messages__Credentials, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbauth__authenticator__messages__credentials__field_indices_by_name[] = {
  1,   /* field[1] = password */
  0,   /* field[0] = user */
};
static const ProtobufCIntRange dbauth__authenticator__messages__credentials__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbauth__authenticator__messages__credentials__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbauth.authenticator.messages.Credentials",
  "Credentials",
  "Dbauth__Authenticator__Messages__Credentials",
  "dbauth.authenticator.messages",
  sizeof(Dbauth__Authenticator__Messages__Credentials),
  2,
  dbauth__authenticator__messages__credentials__field_descriptors,
  dbauth__authenticator__messages__credentials__field_indices_by_name,
  1,  dbauth__authenticator__messages__credentials__number_ranges,
  (ProtobufCMessageInit) dbauth__authenticator__messages__credentials__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbauth__authenticator__messages__authenticate_request__field_descriptors[1] =
{
  {
    "identity",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbauth__Authenticator__Messages__AuthenticateRequest, identity),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbauth__authenticator__messages__authenticate_request__field_indices_by_name[] = {
  0,   /* field[0] = identity */
};
static const ProtobufCIntRange dbauth__authenticator__messages__authenticate_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbauth__authenticator__messages__authenticate_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbauth.authenticator.messages.AuthenticateRequest",
  "AuthenticateRequest",
  "Dbauth__Authenticator__Messages__AuthenticateRequest",
  "dbauth.authenticator.messages",
  sizeof(Dbauth__Authenticator__Messages__AuthenticateRequest),
  1,
  dbauth__authenticator__messages__authenticate_request__field_descriptors,
  dbauth__authenticator__messages__authenticate_request__field_indices_by_name,
  1,  dbauth__authenticator__messages__authenticate_request__number_ranges,
  (ProtobufCMessageInit) dbauth__authenticator__messages__authenticate_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dbauth__authenticator__messages__authenticate_response__status__enum_values_by_number[2] =
{
  { "ERROR", "DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_RESPONSE__STATUS__ERROR", 0 },
  { "SUCCESS", "DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_RESPONSE__STATUS__SUCCESS", 1 },
};
static const ProtobufCIntRange dbauth__authenticator__messages__authenticate_response__status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex dbauth__authenticator__messages__authenticate_response__status__enum_values_by_name[2] =
{
  { "ERROR", 0 },
  { "SUCCESS", 1 },
};
const ProtobufCEnumDescriptor dbauth__authenticator__messages__authenticate_response__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dbauth.authenticator.messages.AuthenticateResponse.Status",
  "Status",
  "Dbauth__Authenticator__Messages__AuthenticateResponse__Status",
  "dbauth.authenticator.messages",
  2,
  dbauth__authenticator__messages__authenticate_response__status__enum_values_by_number,
  2,
  dbauth__authenticator__messages__authenticate_response__status__enum_values_by_name,
  1,
  dbauth__authenticator__messages__authenticate_response__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor dbauth__authenticator__messages__authenticate_response__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbauth__Authenticator__Messages__AuthenticateResponse, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbauth__Authenticator__Messages__AuthenticateResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "credentials",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Dbauth__Authenticator__Messages__AuthenticateResponse, credentials),
    &dbauth__authenticator__messages__credentials__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbauth__authenticator__messages__authenticate_response__field_indices_by_name[] = {
  2,   /* field[2] = credentials */
  1,   /* field[1] = message */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange dbauth__authenticator__messages__authenticate_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dbauth__authenticator__messages__authenticate_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbauth.authenticator.messages.AuthenticateResponse",
  "AuthenticateResponse",
  "Dbauth__Authenticator__Messages__AuthenticateResponse",
  "dbauth.authenticator.messages",
  sizeof(Dbauth__Authenticator__Messages__AuthenticateResponse),
  3,
  dbauth__authenticator__messages__authenticate_response__field_descriptors,
  dbauth__authenticator__messages__authenticate_response__field_indices_by_name,
  1,  dbauth__authenticator__messages__authenticate_response__number_ranges,
  (ProtobufCMessageInit) dbauth__authenticator__messages__authenticate_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor dbauth__authenticator__messages__authenticator__method_descriptors[1] =
{
  { "Authenticate", &dbauth__authenticator__messages__authenticate_request__descriptor, &dbauth__authenticator__messages__authenticate_response__descriptor },
};
const unsigned dbauth__authenticator__messages__authenticator__method_indices_by_name[] = {
  0         /* Authenticate */
};
const ProtobufCServiceDescriptor dbauth__authenticator__messages__authenticator__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "dbauth.authenticator.messages.Authenticator",
  "Authenticator",
  "Dbauth__Authenticator__Messages__Authenticator",
  "dbauth.authenticator.messages",
  1,
  dbauth__authenticator__messages__authenticator__method_descriptors,
  dbauth__authenticator__messages__authenticator__method_indices_by_name
};
void dbauth__authenticator__messages__authenticator__authenticate(ProtobufCService *service,
                                                                  const Dbauth__Authenticator__Messages__AuthenticateRequest *input,
                                                                  Dbauth__Authenticator__Messages__AuthenticateResponse_Closure closure,
                                                                  void *closure_data)
{
  assert(service->descriptor == &dbauth__authenticator__messages__authenticator__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void dbauth__authenticator__messages__authenticator__init (Dbauth__Authenticator__Messages__Authenticator_Service *service,
                                                           Dbauth__Authenticator__Messages__Authenticator_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &dbauth__authenticator__messages__authenticator__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
