/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: authenticator/messages/authenticator.proto */

#ifndef PROTOBUF_C_authenticator_2fmessages_2fauthenticator_2eproto__INCLUDED
#define PROTOBUF_C_authenticator_2fmessages_2fauthenticator_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Dbauth__Authenticator__Messages__Credentials Dbauth__Authenticator__Messages__Credentials;
typedef struct _Dbauth__Authenticator__Messages__AuthenticateRequest Dbauth__Authenticator__Messages__AuthenticateRequest;
typedef struct _Dbauth__Authenticator__Messages__AuthenticateResponse Dbauth__Authenticator__Messages__AuthenticateResponse;


/* --- enums --- */

typedef enum _Dbauth__Authenticator__Messages__AuthenticateResponse__Status {
  DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_RESPONSE__STATUS__ERROR = 0,
  DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_RESPONSE__STATUS__SUCCESS = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_RESPONSE__STATUS)
} Dbauth__Authenticator__Messages__AuthenticateResponse__Status;

/* --- messages --- */

struct  _Dbauth__Authenticator__Messages__Credentials
{
  ProtobufCMessage base;
  char *user;
  char *hashedpassword;
};
#define DBAUTH__AUTHENTICATOR__MESSAGES__CREDENTIALS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbauth__authenticator__messages__credentials__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Dbauth__Authenticator__Messages__AuthenticateRequest
{
  ProtobufCMessage base;
  char *identity;
  char *salt;
};
#define DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbauth__authenticator__messages__authenticate_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Dbauth__Authenticator__Messages__AuthenticateResponse
{
  ProtobufCMessage base;
  Dbauth__Authenticator__Messages__AuthenticateResponse__Status status;
  char *message;
  Dbauth__Authenticator__Messages__Credentials *credentials;
};
#define DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbauth__authenticator__messages__authenticate_response__descriptor) \
    , DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATE_RESPONSE__STATUS__ERROR, (char *)protobuf_c_empty_string, NULL }


/* Dbauth__Authenticator__Messages__Credentials methods */
void   dbauth__authenticator__messages__credentials__init
                     (Dbauth__Authenticator__Messages__Credentials         *message);
size_t dbauth__authenticator__messages__credentials__get_packed_size
                     (const Dbauth__Authenticator__Messages__Credentials   *message);
size_t dbauth__authenticator__messages__credentials__pack
                     (const Dbauth__Authenticator__Messages__Credentials   *message,
                      uint8_t             *out);
size_t dbauth__authenticator__messages__credentials__pack_to_buffer
                     (const Dbauth__Authenticator__Messages__Credentials   *message,
                      ProtobufCBuffer     *buffer);
Dbauth__Authenticator__Messages__Credentials *
       dbauth__authenticator__messages__credentials__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbauth__authenticator__messages__credentials__free_unpacked
                     (Dbauth__Authenticator__Messages__Credentials *message,
                      ProtobufCAllocator *allocator);
/* Dbauth__Authenticator__Messages__AuthenticateRequest methods */
void   dbauth__authenticator__messages__authenticate_request__init
                     (Dbauth__Authenticator__Messages__AuthenticateRequest         *message);
size_t dbauth__authenticator__messages__authenticate_request__get_packed_size
                     (const Dbauth__Authenticator__Messages__AuthenticateRequest   *message);
size_t dbauth__authenticator__messages__authenticate_request__pack
                     (const Dbauth__Authenticator__Messages__AuthenticateRequest   *message,
                      uint8_t             *out);
size_t dbauth__authenticator__messages__authenticate_request__pack_to_buffer
                     (const Dbauth__Authenticator__Messages__AuthenticateRequest   *message,
                      ProtobufCBuffer     *buffer);
Dbauth__Authenticator__Messages__AuthenticateRequest *
       dbauth__authenticator__messages__authenticate_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbauth__authenticator__messages__authenticate_request__free_unpacked
                     (Dbauth__Authenticator__Messages__AuthenticateRequest *message,
                      ProtobufCAllocator *allocator);
/* Dbauth__Authenticator__Messages__AuthenticateResponse methods */
void   dbauth__authenticator__messages__authenticate_response__init
                     (Dbauth__Authenticator__Messages__AuthenticateResponse         *message);
size_t dbauth__authenticator__messages__authenticate_response__get_packed_size
                     (const Dbauth__Authenticator__Messages__AuthenticateResponse   *message);
size_t dbauth__authenticator__messages__authenticate_response__pack
                     (const Dbauth__Authenticator__Messages__AuthenticateResponse   *message,
                      uint8_t             *out);
size_t dbauth__authenticator__messages__authenticate_response__pack_to_buffer
                     (const Dbauth__Authenticator__Messages__AuthenticateResponse   *message,
                      ProtobufCBuffer     *buffer);
Dbauth__Authenticator__Messages__AuthenticateResponse *
       dbauth__authenticator__messages__authenticate_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbauth__authenticator__messages__authenticate_response__free_unpacked
                     (Dbauth__Authenticator__Messages__AuthenticateResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Dbauth__Authenticator__Messages__Credentials_Closure)
                 (const Dbauth__Authenticator__Messages__Credentials *message,
                  void *closure_data);
typedef void (*Dbauth__Authenticator__Messages__AuthenticateRequest_Closure)
                 (const Dbauth__Authenticator__Messages__AuthenticateRequest *message,
                  void *closure_data);
typedef void (*Dbauth__Authenticator__Messages__AuthenticateResponse_Closure)
                 (const Dbauth__Authenticator__Messages__AuthenticateResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Dbauth__Authenticator__Messages__Authenticator_Service Dbauth__Authenticator__Messages__Authenticator_Service;
struct _Dbauth__Authenticator__Messages__Authenticator_Service
{
  ProtobufCService base;
  void (*authenticate)(Dbauth__Authenticator__Messages__Authenticator_Service *service,
                       const Dbauth__Authenticator__Messages__AuthenticateRequest *input,
                       Dbauth__Authenticator__Messages__AuthenticateResponse_Closure closure,
                       void *closure_data);
};
typedef void (*Dbauth__Authenticator__Messages__Authenticator_ServiceDestroy)(Dbauth__Authenticator__Messages__Authenticator_Service *);
void dbauth__authenticator__messages__authenticator__init (Dbauth__Authenticator__Messages__Authenticator_Service *service,
                                                           Dbauth__Authenticator__Messages__Authenticator_ServiceDestroy destroy);
#define DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATOR__BASE_INIT \
    { &dbauth__authenticator__messages__authenticator__descriptor, protobuf_c_service_invoke_internal, NULL }
#define DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATOR__INIT(function_prefix__) \
    { DBAUTH__AUTHENTICATOR__MESSAGES__AUTHENTICATOR__BASE_INIT,\
      function_prefix__ ## authenticate  }
void dbauth__authenticator__messages__authenticator__authenticate(ProtobufCService *service,
                                                                  const Dbauth__Authenticator__Messages__AuthenticateRequest *input,
                                                                  Dbauth__Authenticator__Messages__AuthenticateResponse_Closure closure,
                                                                  void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dbauth__authenticator__messages__credentials__descriptor;
extern const ProtobufCMessageDescriptor dbauth__authenticator__messages__authenticate_request__descriptor;
extern const ProtobufCMessageDescriptor dbauth__authenticator__messages__authenticate_response__descriptor;
extern const ProtobufCEnumDescriptor    dbauth__authenticator__messages__authenticate_response__status__descriptor;
extern const ProtobufCServiceDescriptor dbauth__authenticator__messages__authenticator__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_authenticator_2fmessages_2fauthenticator_2eproto__INCLUDED */
